/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MoneyTracker;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.DefaultListModel;

/**
 *
 * @author slvai_000
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private MTUser currUser;
    private final UserManager userManager;
    private final DefaultListModel<String> defaultListModel = new DefaultListModel<>();

    public MainJFrame() {
        userManager = new UserManager();
        //some stufff
        initComponents();
    }


    private void clearJTextFields(JPanel panel) {
        Component[] components = panel.getComponents();
        for (Component component : components) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            }
        }
    }

    private void login() {
        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "card6");
        clearJTextFields(registration);
        clearJTextFields(login);
        updateStats();
    }

    private void logout() {
        currUser = null;
        defaultListModel.removeAllElements();
        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "card1");
    }

    private void updateStats() {
        statsUsn.setText(currUser.getUsername());
        statsMostCom.setText(currUser.getMost(true));
        statsMostSpent.setText(currUser.getMost(false));

        jLabel12.setText(Integer.toString(currUser.getBudget()));
        listPurchases();
    }

    private void listPurchases() {
        int totalUserEntr = currUser.getTotalEntries();
        int difference = totalUserEntr-defaultListModel.size();
        switch(difference){
            case 1: 
                defaultListModel.add(0, currUser.getEntryData(totalUserEntr-1));
                break;
            case 0:
                break;
            default:
                defaultListModel.removeAllElements();
                for(int a=0; a<totalUserEntr;a++){
                    defaultListModel.add(0, currUser.getEntryData(a));                
                }
                break;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        firstPanel = new javax.swing.JPanel();
        regButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        registration = new javax.swing.JPanel();
        regUsnField = new javax.swing.JTextField();
        regAgeField = new javax.swing.JTextField();
        regBudgetField = new javax.swing.JTextField();
        regPassField = new javax.swing.JPasswordField();
        regBackButton = new javax.swing.JButton();
        regContinueButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        logUsnField = new javax.swing.JTextField();
        logPasswordField = new javax.swing.JPasswordField();
        logBackButton = new javax.swing.JButton();
        logContinueLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mainPane = new javax.swing.JTabbedPane();
        purchases = new javax.swing.JPanel();
        pName = new javax.swing.JTextField();
        pPrice = new javax.swing.JTextField();
        pAddButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pExpenditure = new javax.swing.JRadioButton();
        pExpenditure.setSelected(true);
        pIncome = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pLogoutButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pList = new javax.swing.JList();
        stats = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        statsLogoutButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        statsUsn = new javax.swing.JLabel();
        statsMostCom = new javax.swing.JLabel();
        statsMostSpent = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        statsList = new javax.swing.JList();
        loans = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        loansLogoutButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        loansUsn = new javax.swing.JLabel();
        loansMostCom = new javax.swing.JLabel();
        loansMostSpent = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        loansList = new javax.swing.JList();
        jLabel21 = new javax.swing.JLabel();
        loansMostSpent1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        regButton.setText("Register");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstPanelLayout = new javax.swing.GroupLayout(firstPanel);
        firstPanel.setLayout(firstPanelLayout);
        firstPanelLayout.setHorizontalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        firstPanelLayout.setVerticalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstPanelLayout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(188, 188, 188))
        );

        getContentPane().add(firstPanel, "card1");

        regBackButton.setText("Back");
        regBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBackButtonActionPerformed(evt);
            }
        });

        regContinueButton.setText("Register");
        regContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regContinueButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Starting budget:");

        jLabel3.setText("Password:");

        jLabel4.setText("Age:");

        javax.swing.GroupLayout registrationLayout = new javax.swing.GroupLayout(registration);
        registration.setLayout(registrationLayout);
        registrationLayout.setHorizontalGroup(
            registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registrationLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(regBudgetField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registrationLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regUsnField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrationLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrationLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(233, 233, 233))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(regContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        registrationLayout.setVerticalGroup(
            registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regUsnField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBudgetField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        regPassField.getAccessibleContext().setAccessibleName("");

        getContentPane().add(registration, "card2");

        logUsnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logUsnFieldActionPerformed(evt);
            }
        });

        logBackButton.setText("Back");
        logBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBackButtonActionPerformed(evt);
            }
        });

        logContinueLogin.setText("Login");
        logContinueLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logContinueLoginActionPerformed(evt);
            }
        });

        jLabel5.setText("Username:");

        jLabel9.setText("Password:");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(logBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270)
                        .addComponent(logContinueLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(167, 167, 167)
                                .addComponent(logPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(163, 163, 163)
                                .addComponent(logUsnField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(139, 139, 139))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logUsnField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logContinueLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(login, "card3");

        purchases.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameActionPerformed(evt);
            }
        });
        purchases.add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 84, 170, 40));

        pPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPriceActionPerformed(evt);
            }
        });
        purchases.add(pPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 142, 170, 40));

        pAddButton.setText("Add");
        pAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAddButtonActionPerformed(evt);
            }
        });
        purchases.add(pAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 285, 170, 50));

        jLabel6.setText("Price:");
        purchases.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 152, -1, -1));

        jLabel7.setText("Name:");
        purchases.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 94, -1, -1));

        jLabel8.setText("Budget:");
        purchases.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 25, -1, 38));

        buttonGroup1.add(pExpenditure);
        pExpenditure.setText("Expenditure");
        pExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pExpenditureActionPerformed(evt);
            }
        });
        purchases.add(pExpenditure, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 218, -1, -1));

        buttonGroup1.add(pIncome);
        pIncome.setText("Income");
        purchases.add(pIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 218, -1, -1));

        jLabel10.setText("Purchases:");
        purchases.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 25, -1, -1));

        jLabel12.setText("jLabel12");
        purchases.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 25, 170, 38));

        pLogoutButton.setText("Log out");
        pLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pLogoutButtonActionPerformed(evt);
            }
        });
        purchases.add(pLogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 353, -1, -1));

        pList.setModel(defaultListModel);
        jScrollPane3.setViewportView(pList);

        purchases.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 207, 250));

        mainPane.addTab("Add purchase", purchases);

        stats.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Purchases:");
        stats.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 25, -1, -1));

        statsLogoutButton.setText("Log out");
        statsLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsLogoutButtonActionPerformed(evt);
            }
        });
        stats.add(statsLogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 350, -1, -1));

        jLabel13.setText("Most common purchase:");
        stats.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 97, -1, -1));

        jLabel14.setText("Most money spent on:");
        stats.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 172, -1, -1));

        jLabel15.setText("Username:");
        stats.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 25, -1, -1));

        statsUsn.setText("jLabel16");
        stats.add(statsUsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 25, -1, -1));

        statsMostCom.setText("jLabel17");
        stats.add(statsMostCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 97, -1, -1));

        statsMostSpent.setText("jLabel18");
        stats.add(statsMostSpent, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 172, -1, -1));

        statsList.setModel(defaultListModel);
        jScrollPane4.setViewportView(statsList);

        stats.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 82, 207, 250));

        mainPane.addTab("View statistics", stats);

        jLabel17.setText("Loan:");

        loansLogoutButton.setText("Log out");
        loansLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loansLogoutButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Total value:");

        jLabel19.setText("Monthly payment:");

        jLabel20.setText("Username:");

        loansUsn.setText("jLabel16");

        loansMostCom.setText("jLabel17");

        loansMostSpent.setText("jLabel18");

        loansList.setModel(defaultListModel);
        jScrollPane2.setViewportView(loansList);

        jLabel21.setText("Yearly interest:");

        loansMostSpent1.setText("jLabel18");

        javax.swing.GroupLayout loansLayout = new javax.swing.GroupLayout(loans);
        loans.setLayout(loansLayout);
        loansLayout.setHorizontalGroup(
            loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loansLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loansLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(loansUsn)
                        .addGap(307, 307, 307)
                        .addComponent(jLabel17))
                    .addGroup(loansLayout.createSequentialGroup()
                        .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loansLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(loansMostCom))
                            .addGroup(loansLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(loansMostSpent))
                            .addGroup(loansLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(loansMostSpent1)))
                        .addGap(256, 256, 256)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loansLogoutButton)))
        );
        loansLayout.setVerticalGroup(
            loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loansLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(loansUsn))
                    .addComponent(jLabel17))
                .addGap(37, 37, 37)
                .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loansLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(loansMostCom))
                        .addGap(55, 55, 55)
                        .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(loansMostSpent))
                        .addGap(55, 55, 55)
                        .addGroup(loansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(loansMostSpent1))))
                .addGap(21, 21, 21)
                .addComponent(loansLogoutButton))
        );

        mainPane.addTab("Loans", loans);

        getContentPane().add(mainPane, "card6");

        getAccessibleContext().setAccessibleName("mainPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "card2");
    }//GEN-LAST:event_regButtonActionPerformed

    private void regContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regContinueButtonActionPerformed
        // TODO add your handling code here:
        try {
            currUser = (MTUser)userManager.registerUser(regUsnField.getText(), regPassField.getPassword(), Integer.parseInt(regAgeField.getText()), Integer.parseInt(regBudgetField.getText()));
            JOptionPane.showMessageDialog(this, "Registration successful");
            clearJTextFields(registration);
            this.login();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Incorrect age or budget, please try again");
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_regContinueButtonActionPerformed

    private void regBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBackButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "card1");
    }//GEN-LAST:event_regBackButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "card3");
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBackButtonActionPerformed
        // TODO add your handling code here:        
        CardLayout card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "card1");
    }//GEN-LAST:event_logBackButtonActionPerformed

    private void logContinueLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logContinueLoginActionPerformed
        try {
            currUser = (MTUser) userManager.performLogin(logUsnField.getText(), logPasswordField.getPassword());
            this.login();
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_logContinueLoginActionPerformed

    private void logUsnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logUsnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logUsnFieldActionPerformed

    private void pNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameActionPerformed

    private void pPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPriceActionPerformed

    private void pAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAddButtonActionPerformed
        try {
            currUser.addEntry(pIncome.isSelected(), pName.getText(), Integer.parseInt(pPrice.getText()));
            updateStats();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Incorrect price, please try again");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Something went wrong, please try again");
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_pAddButtonActionPerformed

    private void pExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pExpenditureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pExpenditureActionPerformed

    private void pLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pLogoutButtonActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_pLogoutButtonActionPerformed

    private void statsLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsLogoutButtonActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_statsLogoutButtonActionPerformed

    private void loansLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loansLogoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loansLogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel loans;
    private javax.swing.JList loansList;
    private javax.swing.JButton loansLogoutButton;
    private javax.swing.JLabel loansMostCom;
    private javax.swing.JLabel loansMostSpent;
    private javax.swing.JLabel loansMostSpent1;
    private javax.swing.JLabel loansUsn;
    private javax.swing.JButton logBackButton;
    private javax.swing.JButton logContinueLogin;
    private javax.swing.JPasswordField logPasswordField;
    private javax.swing.JTextField logUsnField;
    private javax.swing.JPanel login;
    private javax.swing.JButton loginButton;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JButton pAddButton;
    private javax.swing.JRadioButton pExpenditure;
    private javax.swing.JRadioButton pIncome;
    private javax.swing.JList pList;
    private javax.swing.JButton pLogoutButton;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField pPrice;
    private javax.swing.JPanel purchases;
    private javax.swing.JTextField regAgeField;
    private javax.swing.JButton regBackButton;
    private javax.swing.JTextField regBudgetField;
    private javax.swing.JButton regButton;
    private javax.swing.JButton regContinueButton;
    private javax.swing.JPasswordField regPassField;
    private javax.swing.JTextField regUsnField;
    private javax.swing.JPanel registration;
    private javax.swing.JPanel stats;
    private javax.swing.JList statsList;
    private javax.swing.JButton statsLogoutButton;
    private javax.swing.JLabel statsMostCom;
    private javax.swing.JLabel statsMostSpent;
    private javax.swing.JLabel statsUsn;
    // End of variables declaration//GEN-END:variables
}
